server:
  port: 8080

# JWT Configuration (debe ser el mismo que en microservice-user)
jwt:
  secret: myVerySecretKeyForAppAgenditaUserService2024

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Ruta para autenticación (login)
        - id: auth
          uri: http://localhost:8070
          predicates:
            - Path=/api/auth/**
        # Ruta para usuarios
        - id: users
          uri: http://localhost:8070
          predicates:
            - Path=/api/users/**
        # Ruta para tareas
        - id: tasks
          uri: http://localhost:8071
          predicates:
            - Path=/api/tasks/**
        # Rutas para futuros microservicios
        - id: notes
          uri: http://localhost:9090
          predicates:
            - Path=/api/notes/**
        - id: events
          uri: http://localhost:9091
          predicates:
            - Path=/api/events/**
      # Configuración global de CORS
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
