server:
  port: 8080

# JWT Configuration (debe ser el mismo que en microservice-user)
jwt:
  secret: myVerySecretKeyForAppAgenditaUserService2024

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Ruta para autenticación (login)
        - id: auth
          uri: lb://msvc-user
          predicates:
            - Path=/api/auth/**
        # Ruta para usuarios
        - id: users
          uri: lb://msvc-user
          predicates:
            - Path=/api/users/**
        # Ruta para tareas
        - id: tasks
          uri: lb://msvc-task
          predicates:
            - Path=/api/tasks/**
        # Rutas para futuros microservicios
        - id: notes
          uri: lb://msvc-note
          predicates:
            - Path=/api/notes/**
        - id: events
          uri: lb://msvc-event
          predicates:
            - Path=/api/events/**
      # Configuración global de CORS
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
