server:
  port: ${PORT:8083}
spring:
  application:
    name: msvc-note
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

# JWT Configuration - IMPORTANTE!
jwt:
  secret: MiClaveSecretaSuperSeguraParaJWTQueDebeSerMuyLargaParaHS512AlMenos64Caracteres123456789
  expiration: 86400000

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false