server:
  port: ${PORT:8080}

# JWT Configuration (debe ser el mismo que en microservice-user)
jwt:
  secret: myVerySecretKeyForAppAgenditaUserService2024

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # Ruta para autenticación (login)
        - id: auth
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
        # Ruta para usuarios
        - id: users
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**
        # Ruta para tareas
        - id: tasks
          uri: http://localhost:8071
          predicates:
            - Path=/api/tasks/**
        # Rutas para futuros microservicios
        - id: notes
          uri: http://localhost:8072
          predicates:
            - Path=/api/notes/**
        - id: events
          uri: http://localhost:8073
          predicates:
            - Path=/api/events/**

---
# Configuración para el perfil de producción
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # Ruta para autenticación (login)
        - id: auth
          uri: https://msvc-user-749990022458.us-central1.run.app
          predicates:
            - Path=/api/auth/**
        # Ruta para usuarios
        - id: users
          uri: https://msvc-user-749990022458.us-central1.run.app
          predicates:
            - Path=/api/users/**
        # Ruta para tareas
        - id: tasks
          uri: https://msvc-task-749990022458.us-central1.run.app
          predicates:
            - Path=/api/tasks/**
        # Rutas para futuros microservicios
        - id: notes
          uri: https://msvc-note-749990022458.us-central1.run.app
          predicates:
            - Path=/api/notes/**
        - id: events
          uri: https://msvc-event-749990022458.us-central1.run.app
          predicates:
            - Path=/api/events/**
      # Configuración global de CORS
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
