server:
  port: 9091
spring:
  application:
    name: msvc-event
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://136.119.250.44:3306/agendita_events_dev?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: duoc_uc
    password: <Vsx%P;y1;.$Eu1H
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

# JWT Configuration - IMPORTANTE!
jwt:
  secret: MiClaveSecretaSuperSeguraParaJWTQueDebeSerMuyLargaParaHS512AlMenos64Caracteres123456789
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true